[package]
name = "simple-http-server"
version = "0.2.0"
authors = ["thewawar <thewawar@gmail.com>"]
license = "MIT"
description = "SimpleHTTPServer.py"
keywords = ["simple", "http", "server", "static"]
repository = "https://github.com/TheWaWaR/simple-http-server"

[dependencies]
clap = "2.24.2"
ansi_term = "0.9.0"
chrono = "0.3.1"
pretty-bytes = "0.2.1"
# Iron crates
iron = "^0.5.0"
