[package]
name = "simple-http-server"
version = "0.1.0"
authors = ["thewawar <thewawar@gmail.com>"]

[dependencies]
log = "0.3.8"
env_logger = "0.4.3"
clap = "2.24.2"
handlebars-iron = "0.24.1"
# Iron crates
iron = "^0.5.0"
staticfile = "0.4.0"
router = "0.5.1"
mount = "0.3.0"

[features]
## create a feature in your app
watch = ["handlebars-iron/watch"]

